// clientes/livros-angular/src/app/livro-lista/livro-lista.component.ts
import { Component, OnInit } from '@angular/core';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Editora } from '../editora';
import { Livro } from '../livro';
import { CommonModule } from '@angular/common';


@Component({
  selector: 'app-livro-lista',
  standalone: true,
  imports: [CommonModule],
  templateUrl: './livro-lista.component.html',
  styleUrl: './livro-lista.component.css'
})
export class LivroListaComponent implements OnInit {
  public editoras: Array<Editora> = [];
  public livros: Array<Livro> = [];

  constructor(
    private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
    this.livros = this.servLivros.obterLivros();
  }

  excluir = (codigo: number): void => {
    this.servLivros.excluir(codigo);
    this.livros = this.servLivros.obterLivros();
  };

  obterNome = (codEditora: number): string | undefined => {
    return this.servEditora.getNomeEditora(codEditora);
  }
}

<main class=" mt-4">
    <h2 class="text-start mb-4">Catálogo de Livros</h2>

    <table class="table table-striped table-bordered">
        <thead class="table-dark">
            <tr>
                <th>Título</th>
                <th>Resumo</th>
                <th>Editora</th>
                <th>Autores</th>
            </tr>
        </thead>
        <tbody>
            <tr *ngFor="let livro of livros">
                <td>
                    <ul class="list-group d-flex justify-content-between">
                        <li>{{ livro.titulo }}</li>
                        <li>
                            <button class="btn btn-danger btn-sm ms-2" (click)="excluir(livro.codigo)">
                                Excluir
                            </button>
                        </li>
                    </ul>
                </td>
                <td>{{livro.resumo}}</td>
                <td>{{ obterNome(livro.codEditora) }}</td>
                <td>
                    <ul>
                        <li *ngFor="let autor of livro.autores">{{ autor }}</li>
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>
</main>

// clientes/livros-react/src/LivroLista.js
import React, { useState, useEffect } from 'react';
import ControleLivros from './controle/ControleLivros';
import ControleEditora from './controle/ControleEditora';

const LinhaLivro = ({ livro, excluir }) => {
    const controleEditora = new ControleEditora();
    const nomeEditora = controleEditora.getNomeEditora(livro.codEditora);

    return (
        <tr>
            <td>
                <ul className='list-group'>
                    <li style={{ listStyle: 'none' }}>{livro.título}</li>
                    <li style={{ listStyle: 'none' }}><button className='btn btn-danger' onClick={() => excluir(livro.codigo)}>Excluir</button></li>
                </ul>
            </td>
            <td>{livro.resumo}</td>
            <td>{nomeEditora}</td>

            <td>
                <ul>
                    {livro.autores.map((autor, index) => (
                        <li key={index}>{autor}</li>
                    ))}
                </ul>
            </td>
        </tr>
    );
};

const LivroLista = () => {
    const [livros, setLivros] = useState([]);
    const [carregado, setCarregado] = useState(false);

    useEffect(() => {
        const controleLivros = new ControleLivros();
        controleLivros.obterLivros()
            .then(livrosObtidos => {
                setLivros(livrosObtidos);
                setCarregado(true);
            })
            .catch(error => {
                console.error("Erro ao carregar livros:", error);
                setCarregado(true);
            });
    }, []);

    const excluir = (codigo) => {
        const controleLivros = new ControleLivros();
        controleLivros.excluir(codigo)
            .then(() => {
                setLivros(livros.filter(livro => livro.codigo !== codigo));
                setCarregado(false);
            })
            .catch(error => {
                console.error("Erro ao excluir o livro:", error);
                setCarregado(true);
            });
    };

    return (
        <main className='mx-5'>
            <h1 className='mx-5 d-flex justify-content-start'>Catalogo de Livros</h1>
            <table className='table table-striped'>
                <thead className='table-dark'>
                    <tr>
                        <th >Título</th>
                        <th>Resumo</th>
                        <th>Editora</th>
                        <th>Autores</th>
                    </tr>
                </thead>
                <tbody>
                    {livros.map((livro, index) => (
                        <LinhaLivro
                            key={index}
                            livro={livro}
                            excluir={excluir}
                            index={index} 
                        />
                    ))}
                </tbody>
            </table>
        </main>
    );
};

export default LivroLista;
