// clientes/livros-react/src/LivroDados.js
import ControleEditora from "./controle/ControleEditora";
import ControleLivro from "./controle/ControleLivros";
import { useNavigate } from "react-router-dom";
import { useState, useEffect } from "react";

const LivroDados = () => {
    const controleLivro = new ControleLivro();
    const controleEditora = new ControleEditora();

    const [título, setTitulo] = useState('');
    const [resumo, setResumo] = useState('');
    const [autores, setAutores] = useState('');
    const [opcoes, setOpcoes] = useState([]);
    const [codEditora, setCodEditora] = useState(0);

    const navigate = useNavigate();

    useEffect(() => {
        const editoras = controleEditora.getEditoras();
        const opcoesMapeadas = editoras.map(editora => ({
            value: editora.codEditora,
            text: editora.nome
        }));
        setOpcoes(opcoesMapeadas);

        if (opcoesMapeadas.length > 0) {
            setCodEditora(opcoesMapeadas[0].value);
        }
    }, []);

    const tratarCombo = (evento) => {
        setCodEditora(Number(evento.target.value));
    };

    const incluir = (evento) => {
        evento.preventDefault();
        const novoLivro = {
            codigo: '',
            codEditora: codEditora,
            título: título,
            resumo: resumo,
            autores: autores.split('\n')
        };
        controleLivro.incluir(novoLivro)
            .then(() => {
                navigate('/livros');
            })
            .catch(error => {
                console.error("Erro ao incluir livro:", error);
            });
    }

    return (
        <main>
            <h1 className="d-flex justify-content-start mx-5">Dados do Livro</h1>
            <form onSubmit={incluir} className="mx-5">

                <div className="mb-3">
                    <label htmlFor="título" className="form-label d-flex justify-content-start">Título</label>
                    <input
                        type="text"
                        id="título"
                        className="form-control"
                        value={título}
                        onChange={(evento) => setTitulo(evento.target.value)}
                    />
                </div>

                <div className="mb-3">
                    <label htmlFor="resumo" className="d-flex justify-content-start" >Resumo</label>
                    <textarea
                        id="resumo"
                        className="form-control "
                        value={resumo}
                        onChange={(evento) => setResumo(evento.target.value)}
                    />
                </div>

                <div className="mb-3">
                    <label htmlFor="editora" className="form-label d-flex justify-content-start">Editora</label>
                    <select
                        id="editora"
                        className="form-select"
                        value={codEditora}
                        onChange={tratarCombo}
                    >
                        {opcoes.map((opcao) => (
                            <option key={opcao.value} value={opcao.value}>
                                {opcao.text}
                            </option>
                        ))}
                    </select>
                </div>
                <div className="mb-3">
                    <label htmlFor="autores" className="form-label d-flex justify-content-start">Autores (1 por linha)</label>
                    <textarea
                        id="autores"
                        className="form-control"
                        value={autores}
                        onChange={(evento) => setAutores(evento.target.value)}
                    />
                </div>
                <button type="submit" className="btn btn-primary d-flex justify-content-start">Salvar Dados</button>
            </form>
        </main>
    )
}

export default LivroDados;

// clientes/livros-angular/src/app/livro-dados/livro-dados.component.ts
import { Component, OnInit } from '@angular/core';
import { Livro } from '../livro';
import { Editora } from '../editora';
import { ControleEditoraService } from '../controle-editora.service';
import { ControleLivrosService } from '../controle-livros.service';
import { Router } from '@angular/router';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

@Component({
  selector: 'app-livro-dados',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './livro-dados.component.html',
  styleUrl: './livro-dados.component.css'
})
export class LivroDadosComponent implements OnInit {

  public livro: Livro = new Livro(0, 0, '', '', []);
  public autoresForm: string = '';
  public editoras: Array<Editora> = [];

  constructor(private servEditora: ControleEditoraService,
    private servLivros: ControleLivrosService,
    private router: Router
  ) { }

  ngOnInit(): void {
    this.editoras = this.servEditora.getEditoras();
  }

  incluir = (): void => {
    this.livro.autores = this.autoresForm.split('\n');
    this.livro.codEditora = Number(this.livro.codEditora);
    this.servLivros.incluir(this.livro);
    this.router.navigateByUrl('/lista')
    console.log(this.livro)
  }
}




<main class="container mt-4">
    <h2>Incluir Novo Livro</h2>

    <form (submit)="incluir()" ngNativeValidate class="needs-validation">
        <div class="mb-3">
            <label for="titulo" class="form-label">Título</label>
            <input type="text" id="titulo" class="form-control" required [(ngModel)]="livro.titulo" name="titulo" />
        </div>

        <div class="mb-3">
            <label for="resumo" class="form-label">Resumo</label>
            <textarea id="resumo" class="form-control" rows="3" [(ngModel)]="livro.resumo" name="resumo"></textarea>
        </div>

        <div class="mb-3">
            <label for="editora" class="form-label">Editora</label>
            <select id="editora" class="form-select" [(ngModel)]="livro.codEditora" name="editora" required>
                <option *ngFor="let editora of editoras" [value]="editora.codEditora">
                    {{ editora.nome }}
                </option>
            </select>
        </div>

        <div class="mb-3">
            <label for="autores" class="form-label">Autores (um por linha)</label>
            <textarea id="autores" class="form-control" rows="3" [(ngModel)]="autoresForm" name="autores"></textarea>
        </div>

        <button type="submit" class="btn btn-primary">Incluir Livro</button>
    </form>
</main>
